### ISSUE TITLE
Does Not Go Past Splash Screen

### ISSUE THREAD

**Issue by nickspurry** [microsoft/fluent-xaml-theme-editor#41] opened 2020-05-24 04:47 UTC
When opened, Fluent XAML Theme Editor does not progress past the initial blue screen with the app logo in the center. App was obtained from Microsoft Store.

App is running on Windows 10 1909. System language is set to French.

**Comment by hansmbakker** [comment] 2020-05-24 08:26
Duplicate of #34

**Comment by kikisaints** [comment] 2020-06-04 18:06
French was the first localization error to find this, however I cannot track down the root cause of it. Closing because of dupe, however. I am sorry you're running into this...

**Closed by kikisaints** 2020-06-04 18:06 UTC
