### ISSUE TITLE
Color scheme is not applied to all elements

### ISSUE THREAD

**Issue by lhak** [Microsoft/fluent-xaml-theme-editor#6] opened 2018-10-09 13:09 UTC
The selected color scheme is not applied to all elements, e.g. the selected combobox item always uses the system accent color.

**Comment by pablojimpas** [comment] 2018-10-09 16:43
I can reproduce it. I've seen this issue in some areas of ComboBox, TextBox, CalendarView, DatePicker and TimePicker.  
This issue is happening both in dark and light themes, maybe is a SDK related issue due to how color properties are set UI controls.  
  
Some screenshots: 
![1](https://user-images.githubusercontent.com/17835916/46684212-74fc0e00-cbf2-11e8-88b1-bb659ee5c4ef.png)
![2](https://user-images.githubusercontent.com/17835916/46684214-74fc0e00-cbf2-11e8-8243-470c86d697a0.png)

**Comment by kikisaints** [comment] 2018-10-09 20:29
It's actually not an issue with the editor, so much as it is with where we insert popups in the visual tree.

In this app, the ColorPaletteResources API also allows you to scope color resources to a container or element's resource scope. Meaning in the case of the editor, we're scoping all your chosen theme colors to the two main areas (in red/green lines below):

![image](https://user-images.githubusercontent.com/6964369/46696107-3bada900-cbc6-11e8-89af-e2d7a905efb4.png)

*However* when you trigger a popup in the XAML framework, we do not insert that popup within the scope of the control that triggered it. Instead we insert it much higher in the visual tree. Thus outside of the scope of what our ColorPalleteResources API is affecting.

The reason we scoped the API to just the light/dark theme panels was to prevent the Color dictionary panel on the right side from getting affected by your theme changes when you edit it in the app. We felt that that would be disorienting.

This shouldn't be an issue when you export and use the theme, however. If you put your exported theme code at the app.xaml level, or just defining the AccentColor property at the app.xaml level, will theme all your popups in your app as well.

**Comment by lhak** [comment] 2018-10-09 22:02
Thank you very much for the detailed explanation. I still think that the items of the combox visually should have the same look as the combox itself. Otherwise, this leads to a really inconsistent look as can already be seen in the editor app.

I also tried to define the accent color in App.xaml but this does not change the color of the selected combobox item (it is still the system accent color). Additionally, adding the WinUI library reverts the accent color to the system default one in even more places (e.g. toggle switches).

**Comment by kikisaints** [comment] 2018-10-09 23:00
Hmm, I'll see what I can do about the editor - but as far as your issue with the accent color not working in App.xaml, could you provide your code + markup? I'll take a look.

**Comment by lhak** [comment] 2018-10-10 08:06
To reproduce the issue create a new universal project  (SDK 17763 and running on Windows 17763). Then change these files accordingly:

App.xaml:


`<Application
    x:Class="AccentColorTest.App"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:AccentColorTest">
	<Application.Resources>
		<ResourceDictionary>
			<ResourceDictionary.ThemeDictionaries>
				<ResourceDictionary x:Key="Default">
					<Color x:Key="SystemAccentColor">#FFFFFF00</Color>
				</ResourceDictionary>
			</ResourceDictionary.ThemeDictionaries>
		</ResourceDictionary>
	</Application.Resources>
</Application>
`

**Comment by mdtauk** [comment] 2018-10-10 12:43
You don't seem to have copied the XAML that the tool produces.  Also it needs to be running on the 1809 release.

I see none of the **ColorPaletteResources** entries.

Here is an example of the full output you need to include in the App.xaml
`
<ResourceDictionary.ThemeDictionaries>
    <ResourceDictionary x:Key="Default">
        <ResourceDictionary.MergedDictionaries>
            <ColorPaletteResources Accent="#FFBFCF36" AltHigh="#FF000000" AltLow="#FF000000" AltMedium="#FF000000" AltMediumHigh="#FF000000" AltMediumLow="#FF000000" BaseHigh="#FFFFFFFF" BaseLow="#FF333333" BaseMedium="#FF9A9A9A" BaseMediumHigh="#FFB4B4B4" BaseMediumLow="#FF676767" ChromeAltLow="#FFB4B4B4" ChromeBlackHigh="#FF000000" ChromeBlackLow="#FFB4B4B4" ChromeBlackMedium="#FF000000" ChromeBlackMediumLow="#FF000000" ChromeDisabledHigh="#FF333333" ChromeDisabledLow="#FF9A9A9A" ChromeGray="#FF808080" ChromeHigh="#FF808080" ChromeLow="#FF151515" ChromeMedium="#FF1D1D1D" ChromeMediumLow="#FF2C2C2C" ChromeWhite="#FFFFFFFF" ListLow="#FF1D1D1D" ListMedium="#FF333333" />
            <ResourceDictionary>
                <Color x:Key="RegionColor">#FF000000</Color>
                <SolidColorBrush x:Key="RegionBrush" Color="{StaticResource RegionColor}" />
            </ResourceDictionary>
        </ResourceDictionary.MergedDictionaries>
    </ResourceDictionary>
    <ResourceDictionary x:Key="Light">
        <ResourceDictionary.MergedDictionaries>
            <ColorPaletteResources Accent="#FFBFCF36" AltHigh="#FFFFFFFF" AltLow="#FFFFFFFF" AltMedium="#FFFFFFFF" AltMediumHigh="#FFFFFFFF" AltMediumLow="#FFFFFFFF" BaseHigh="#FF000000" BaseLow="#FFCCCCCC" BaseMedium="#FF898989" BaseMediumHigh="#FF5D5D5D" BaseMediumLow="#FF737373" ChromeAltLow="#FF5D5D5D" ChromeBlackHigh="#FF000000" ChromeBlackLow="#FFCCCCCC" ChromeBlackMedium="#FF5D5D5D" ChromeBlackMediumLow="#FF898989" ChromeDisabledHigh="#FFCCCCCC" ChromeDisabledLow="#FF898989" ChromeGray="#FF737373" ChromeHigh="#FFCCCCCC" ChromeLow="#FFECECEC" ChromeMedium="#FFE6E6E6" ChromeMediumLow="#FFECECEC" ChromeWhite="#FFFFFFFF" ListLow="#FFE6E6E6" ListMedium="#FFCCCCCC" />
            <ResourceDictionary>
                <Color x:Key="RegionColor">#FFFFFFFF</Color>
                <SolidColorBrush x:Key="RegionBrush" Color="{StaticResource RegionColor}" />
            </ResourceDictionary>
        </ResourceDictionary.MergedDictionaries>
    </ResourceDictionary>
    <ResourceDictionary x:Key="HighContrast">
        <StaticResource x:Key="RegionColor" ResourceKey="SystemColorWindowColor" />
        <SolidColorBrush x:Key="RegionBrush" Color="{StaticResource RegionColor}" />
    </ResourceDictionary>
</ResourceDictionary.ThemeDictionaries>

`

**Comment by lhak** [comment] 2018-10-10 15:23
Adding your code instead of just setting the accent color resource has the same effect: The combobox item and the toggle switch (if the WinUI library is used) still use the default system accent color.

**Comment by kikisaints** [comment] 2018-10-10 17:13
Ah I see what's going on. ComboBox's list items take system-generated (from the user) colors instead of using a variation on the accent color like most of the other controls do.

I'll look into having the editor accomodate these colors, but for the time being @lhak you should be able to do something like this:
```xaml
<Application.Resources>
        <ResourceDictionary>
            <ResourceDictionary.ThemeDictionaries>
                <ResourceDictionary x:Key="Default">
                    <Color x:Key="SystemAccentColorDark3">#FFFFFF00</Color>
                    <Color x:Key="SystemAccentColorDark2">#FFFFFF00</Color>
                    <Color x:Key="SystemAccentColorLight3">#FFFFFF00</Color>
                    <Color x:Key="SystemAccentColorLight2">#FFFFFF00</Color>
            </ResourceDictionary>
            </ResourceDictionary.ThemeDictionaries>
        </ResourceDictionary>
    </Application.Resources>
```

**Comment by lhak** [comment] 2018-10-10 17:35
Thank you, this fixes the issue with the combobox. However, toggle switches still show the system accent color when the WinUI library is added to app.xaml.

**Comment by kikisaints** [comment] 2018-10-10 17:59
Apologies if I'm being rather pedantic, but I need to double check. The following code does not show you the correct accent color?

```xaml
<Application
    x:Class="App13.App"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:winuilib="using:Microsoft.UI.Xaml.Controls"
    xmlns:local="using:App13">

    <Application.Resources>
        <ResourceDictionary>
            <ResourceDictionary.ThemeDictionaries>
                <ResourceDictionary x:Key="Default">                    
                    <Color x:Key="SystemAccentColorDark3">#FFFFFF00</Color>
                    <Color x:Key="SystemAccentColorDark2">#FFFFFF00</Color>
                    <Color x:Key="SystemAccentColorLight3">#FFFFFF00</Color>
                    <Color x:Key="SystemAccentColorLight2">#FFFFFF00</Color>
                    <Color x:Key="SystemAccentColor">#FFFFFF00</Color>
                </ResourceDictionary>
            </ResourceDictionary.ThemeDictionaries>
        </ResourceDictionary>
    </Application.Resources>

</Application>
```

**Comment by lhak** [comment] 2018-10-10 18:30
It does show the right accent color. However, following the WinUI documentation, I changed the code to look like this:

```xaml
<Application.Resources>
		<ResourceDictionary>
			<ResourceDictionary.MergedDictionaries>
				<XamlControlsResources xmlns="using:Microsoft.UI.Xaml.Controls"/>
			</ResourceDictionary.MergedDictionaries>
			<ResourceDictionary.ThemeDictionaries>
				<ResourceDictionary x:Key="Default">
					<Color x:Key="SystemAccentColorDark3">#FFFFFF00</Color>
					<Color x:Key="SystemAccentColorDark2">#FFFFFF00</Color>
					<Color x:Key="SystemAccentColorLight3">#FFFFFF00</Color>
					<Color x:Key="SystemAccentColorLight2">#FFFFFF00</Color>
					<Color x:Key="SystemAccentColor">#FFFFFF00</Color>
				</ResourceDictionary>
			</ResourceDictionary.ThemeDictionaries>
		</ResourceDictionary>
	</Application.Resources>
```

Adding the additional line causes the toggle switch accent color issue:

- Switched on and pointer not over the control: Reverts to system accent color

- Switched on and pointer over the control: Shows the custom accent color

Another control that shows this issue is the TextBox: When selected, the border will be drawn with the system accent color.

**Comment by touseefbsb** [comment] 2018-10-16 00:39
@kikisaints  I just noticed there is an updated version of of winui on nuget ( **2.0.181011001** ) any idea what improvements have been in this update? any breaking changes? or is it safe to upgrade.

**Comment by kikisaints** [comment] 2018-10-16 12:16
It should be safe to upgrade, I made that bump yesterday. It appears to also have fixed the accent color issue that you encountered and described here too.

**Comment by touseefbsb** [comment] 2018-10-16 15:51
everyone from windows community toolkit, windows template studio and theme editor secretly is working on winui :D I just wish it can be opensource so we can be involved directly :)

**Comment by lhak** [comment] 2018-10-16 17:13
Yes, I can confirm that the newest winui version fixes the reported issue, so I guess it can be closed now. Unfortunately, the update seems to cause another (unrelated) styling problem, so I will open a new issue at the winui GitHub repository.

**Comment by kikisaints** [comment] 2018-10-16 18:36
@lhak sounds good! Thank you for bringing issues to our attention though! We appreciate it.

@touseefbsb There's a [repo for WinUI](https://github.com/Microsoft/microsoft-ui-xaml), be sure to go check that out!

**Closed** 2018-10-16 18:37 UTC
